version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    env_file:
      - ./.env
    ports:
      - '8086:8086'
    volumes:
      - ./storages/influxdb-storage:/var/lib/influxdb:rw
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./influxdb-selfsigned.key:/etc/ssl/private/influxdb-selfsigned.key:ro
      - ./influxdb-selfsigned.crt:/etc/ssl/certs/influxdb-selfsigned.crt:ro
    environment:
  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - ./storages/chronograf-storage:/var/lib/chronograf:rw
    depends_on:
      - influxdb
    environment:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - ./storages/grafana-storage:/var/lib/grafana:rw
      - ./grafana-provisioning/:/etc/grafana/provisioning
      - ./influxdb-selfsigned.key:/etc/ssl/private/influxdb-selfsigned.key:ro
      - ./influxdb-selfsigned.crt:/etc/ssl/certs/influxdb-selfsigned.crt:ro
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
      - ./plugins:/var/lib/grafana/plugins
    depends_on:
      - influxdb
